name: Install package and run linter
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  miniconda:
    name: Run linter and test suite
    runs-on: ubuntu-latest
    env:
      HAKAI_API_TOKEN: ${{ secrets.HAKAI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Lint Tests
        shell: bash -l {0}
        run: |
          pip install flake8 pytest pyarrow fastparquet
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install package locally
        run: pip install .
      - name: Pytest
        with:
          CREDENTIAL_TOKEN: ${{ secrets.HAKAI_API_TOKEN }}
        run: pytest
